#!/bin/python3

import sys

def solve(grades,n):
        for i in range (0,n):
                if(grades[i] < 38 or grades[i] % 5 < 3 ): 
                      grades[i]=grades[i] 
                else:
                      grades[i]=grades[i]+(5-(grades[i]%5))
                print (grades[i])
n = int(input().strip())
grades = []
grades_i = 0
for grades_i in range(n):
   grades_t = int(input().strip())
   grades.append(grades_t)
result = solve(grades,n)


